-- SQLite to SQL dump generated by export_sqlite.php
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS `cache`;
CREATE TABLE "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));

INSERT INTO `cache` (`key`,`value`,`expiration`) VALUES ('laravel-cache-luzmyfeliz2002@gmail.com|::1:timer','i:1763848169;','1763848169');
INSERT INTO `cache` (`key`,`value`,`expiration`) VALUES ('laravel-cache-luzmyfeliz2002@gmail.com|::1','i:2;','1763848169');

DROP TABLE IF EXISTS `cache_locks`;
CREATE TABLE "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));

DROP TABLE IF EXISTS `citas`;
CREATE TABLE "citas" ("id" integer primary key AUTO_INCREMENT not null, "paciente_id" integer not null, "fisioterapeuta_id" integer not null, "especialidad_id" integer not null, "fecha" date not null, "hora" time not null, "estado" varchar check ("estado" in ('pendiente', 'confirmada', 'cancelada')) not null default 'pendiente', "motivo" text, "created_at" datetime, "updated_at" datetime, foreign key("paciente_id") references "pacientes"("id") on delete cascade, foreign key("fisioterapeuta_id") references "fisioterapeutas"("id") on delete cascade, foreign key("especialidad_id") references "especialidades"("id") on delete cascade);

DROP TABLE IF EXISTS `especialidades`;
CREATE TABLE "especialidades" ("id" integer primary key AUTO_INCREMENT not null, "nombre" varchar not null, "descripcion" varchar, "created_at" datetime, "updated_at" datetime);

DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE "failed_jobs" ("id" integer primary key AUTO_INCREMENT not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS `fisioterapeutas`;
CREATE TABLE "fisioterapeutas" ("id" integer primary key AUTO_INCREMENT not null, "nombre" varchar not null, "apellido" varchar, "telefono" varchar, "correo" varchar, "especialidad_id" integer, "numero_colegiado" varchar, "password" varchar, "created_at" datetime, "updated_at" datetime, foreign key("especialidad_id") references "especialidades"("id") on delete set null);

DROP TABLE IF EXISTS `historiales_clinicos`;
CREATE TABLE "historiales_clinicos" ("id" integer primary key AUTO_INCREMENT not null, "paciente_id" integer not null, "fisioterapeuta_id" integer, "cita_id" integer, "diagnostico" text, "tratamiento" text, "observaciones" text, "fecha_registro" date not null default '2025-11-22 21:46:10', "created_at" datetime, "updated_at" datetime, foreign key("paciente_id") references "pacientes"("id") on delete cascade, foreign key("fisioterapeuta_id") references "fisioterapeutas"("id") on delete set null, foreign key("cita_id") references "citas"("id") on delete set null);

DROP TABLE IF EXISTS `job_batches`;
CREATE TABLE "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));

DROP TABLE IF EXISTS `jobs`;
CREATE TABLE "jobs" ("id" integer primary key AUTO_INCREMENT not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);

DROP TABLE IF EXISTS `migrations`;
CREATE TABLE "migrations" ("id" integer primary key AUTO_INCREMENT not null, "migration" varchar not null, "batch" integer not null);

INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('1','0001_01_01_000000_create_users_table','1');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('2','0001_01_01_000001_create_cache_table','1');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('3','0001_01_01_000002_create_jobs_table','1');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('4','2025_11_21_205246_...','2');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('5','2025_11_21_205316_crear_tabla_usuarios','2');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('6','2025_11_21_205348_crear_tabla_roles','2');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('7','2025_11_21_205411_crear_tabla_pacientes','2');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('8','2025_11_21_205425_crear_tabla_fisioterapeutas','2');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('9','2025_11_21_205447_crear_tabla_especialidades','2');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('10','2025_11_21_205502_crear_tabla_citas','2');
INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES ('11','2025_11_21_205531_crear_tabla_historiales_clinicos','2');

DROP TABLE IF EXISTS `pacientes`;
CREATE TABLE "pacientes" ("id" integer primary key AUTO_INCREMENT not null, "nombre" varchar not null, "apellido" varchar, "cedula" varchar, "telefono" varchar, "correo" varchar, "fecha_nacimiento" date, "direccion" varchar, "sexo" varchar, "password" varchar, "created_at" datetime, "updated_at" datetime);

DROP TABLE IF EXISTS `password_reset_tokens`;
CREATE TABLE "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));

DROP TABLE IF EXISTS `roles`;
CREATE TABLE "roles" ("id" integer primary key AUTO_INCREMENT not null, "nombre_rol" varchar not null, "descripcion" varchar, "created_at" datetime, "updated_at" datetime);

DROP TABLE IF EXISTS `sessions`;
CREATE TABLE "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));

INSERT INTO `sessions` (`id`,`user_id`,`ip_address`,`user_agent`,`payload`,`last_activity`) VALUES ('oKsZkswqFeJUT9ErwomhhPwogxaibtkNJMw0OsgP',NULL,'::1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0','YTozOntzOjY6Il90b2tlbiI7czo0MDoiYzhRckNyN1JmTUxGMHFKR3NGSkZndFJ1blR2VGNmMWdCRm9hQWM4VSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mzg6Imh0dHA6Ly9sb2NhbGhvc3QvZmlzaW9jYXJlLWF5bGEvcHVibGljIjtzOjU6InJvdXRlIjtOO31zOjY6Il9mbGFzaCI7YToyOntzOjM6Im9sZCI7YTowOnt9czozOiJuZXciO2E6MDp7fX19','1763758131');
INSERT INTO `sessions` (`id`,`user_id`,`ip_address`,`user_agent`,`payload`,`last_activity`) VALUES ('CI5wATKKUGj7hJcUCXze8pezoUfRHj1nD5ZA1jvZ',NULL,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0','YTozOntzOjY6Il90b2tlbiI7czo0MDoiVEVpRDNQNkF6bVhOWjFOSUZGZkJhY0xDb1U0SGUzaGFsVXhHUkcyTCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7czo1OiJyb3V0ZSI7Tjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==','1763790305');
INSERT INTO `sessions` (`id`,`user_id`,`ip_address`,`user_agent`,`payload`,`last_activity`) VALUES ('qIqCylPtVne99W41gzISQ3jTBGQ3XW6DUTXqavmO',NULL,'::1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.106.2 Chrome/138.0.7204.251 Electron/37.7.0 Safari/537.36','YTozOntzOjY6Il90b2tlbiI7czo0MDoieUIwTVU0TVkxN3lSNXoydXJxNnhzVklkMWk3QkZQUTVWVGlJQjVvNyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MTExOiJodHRwOi8vbG9jYWxob3N0L2Zpc2lvY2FyZS1heWxhL3B1YmxpYz9pZD1hODA2YzU5MC0wODQxLTQ2YTEtYjQ2NC05MDgyMzVmOTRhYjUmdnNjb2RlQnJvd3NlclJlcUlkPTE3NjM4NDM0NTM5NjUiO3M6NToicm91dGUiO047fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=','1763843454');
INSERT INTO `sessions` (`id`,`user_id`,`ip_address`,`user_agent`,`payload`,`last_activity`) VALUES ('bhApd6urgvC1IlXPqNqlfRE9n5TaKQXhFnsTHozE','1','::1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0','YTo0OntzOjY6Il90b2tlbiI7czo0MDoiemZXZUswbFgzdHpNVk0wWk11Sjh4ZWlzRm1aRTdVcGM5cFdUcndPRyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NTQ6Imh0dHA6Ly9sb2NhbGhvc3QvZmlzaW9jYXJlLWF5bGEvcHVibGljL2ZvcmdvdC1wYXNzd29yZCI7czo1OiJyb3V0ZSI7czoxNjoicGFzc3dvcmQucmVxdWVzdCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fXM6NTA6ImxvZ2luX3dlYl81OWJhMzZhZGRjMmIyZjk0MDE1ODBmMDE0YzdmNThlYTRlMzA5ODlkIjtpOjE7fQ==','1763848179');

DROP TABLE IF EXISTS `users`;
CREATE TABLE "users" ("id" integer primary key AUTO_INCREMENT not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);

INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`) VALUES ('1','Luz Mayra Feliz','luzmyfeliz2002@gmail.com',NULL,'$2y$12$Av1gSP/HasVhaj2YAzCB5OoqmBTf3Whj92T.Qv0tgulyUoMl4I4Pe',NULL,'2025-11-22 21:43:28','2025-11-22 21:43:28');

DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE "usuarios" ("id" integer primary key AUTO_INCREMENT not null, "nombre" varchar not null, "apellido" varchar, "email" varchar not null, "password" varchar not null, "telefono" varchar, "email_verified_at" datetime, "rol_id" integer not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, foreign key("rol_id") references "roles"("id") on delete cascade);

CREATE UNIQUE INDEX "especialidades_nombre_unique" on "especialidades" ("nombre");

CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");

CREATE UNIQUE INDEX "fisioterapeutas_correo_unique" on "fisioterapeutas" ("correo");

CREATE INDEX "jobs_queue_index" on "jobs" ("queue");

CREATE UNIQUE INDEX "pacientes_cedula_unique" on "pacientes" ("cedula");

CREATE UNIQUE INDEX "pacientes_correo_unique" on "pacientes" ("correo");

CREATE UNIQUE INDEX "roles_nombre_rol_unique" on "roles" ("nombre_rol");

CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");

CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");

CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");

CREATE UNIQUE INDEX "usuarios_email_unique" on "usuarios" ("email");

COMMIT;
